### ISSUE TITLE
License Infromation

### ISSUE THREAD

**Issue by prabin131** [xmba15/superpoint_superglue_deployment#1]
Hi, xmba 15, 
I was working on experimenting various learnable featurematching techniques. I came across your library, and found it handy for quick experimentations. But, I did not see any license information for the use. I was wondering what is the license status for this?

With Regards, 
PG

**Comment by xmba15** [comment]
@prabin131 Thank you for your interest in the code base.
I have added an MIT license to the code base itself. Superpoint weights are provided with an MIT license by the author, but Superglue weights have their non-commercial permit set by the author. Please check the links in the references. Hope this will help your work.
